### ISSUE TITLE
代码输出问题

### ISSUE THREAD

**Issue by MountainShan214** [SuikaXhq/TKGAT#1]
Traceback (most recent call last):
  File "/home/lss/SeverProjects/TKGAT-master/main_tkgat.py", line 363, in <module>
    train(args)
  File "/home/lss/SeverProjects/TKGAT-master/main_tkgat.py", line 243, in train
    _, precision, recall, ndcg = evaluate(model, train_graph, data.train_user_dict, data.valid_user_dict, user_ids_batches, item_ids, args.K)
  File "/home/lss/SeverProjects/TKGAT-master/main_tkgat.py", line 72, in evaluate
    precision_k = np.mean(precision)
  File "<__array_function__ internals>", line 200, in mean
  File "/home/lss/anaconda3/envs/Rec/lib/python3.8/site-packages/numpy/core/fromnumeric.py", line 3464, in mean
    return _methods._mean(a, axis=axis, dtype=dtype,
  File "/home/lss/anaconda3/envs/Rec/lib/python3.8/site-packages/numpy/core/_methods.py", line 165, in _mean
    arr = asanyarray(a)
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

**Comment by MountainShan214** [comment]
作者你好，下载代码运行时出现了维度不匹配问题，还请麻烦解答，谢谢！

**Comment by SuikaXhq** [comment]
可以问一下运行了什么命令吗？

**Comment by MountainShan214** [comment]
你好，问题解决了，现在想问针对Last-fm和delicious在没有物品属性信息情况下是如何生成kg_final的，代码的dataset中只有Movielens有kg_final.txt，谢谢！

**Comment by SuikaXhq** [comment]
物品信息和社交网络都是auxiliary knowledge，同时有这两者的数据集比较少

**Comment by MountainShan214** [comment]
好的，感谢！
